### ISSUE TITLE
[BUG] bg_space -> brainglobe_space

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainglobe-workflows#84]
**Describe the bug**
Reported by @Eddymorphling in https://github.com/brainglobe/brainglobe-workflows/issues/83#issuecomment-1959884804
> when I run `brainmapper -h`, I get the below error.
```

(brainglobe_v2) [ivm@vn2013is10 ~]$ brainmapper -h
Traceback (most recent call last):
  File "/home/ivm/conda/envs/brainglobe_v2/bin/brainmapper", line 5, in <module>
    from brainglobe_workflows.brainmapper.main import main
  File "/home/ivm/conda/envs/brainglobe_v2/lib/python3.10/site-packages/brainglobe_workflows/brainmapper/main.py", line 15, in <module>
    import bg_space as bgs

```

**To Reproduce**
Please enter full details of how to reproduce this bug.

**Expected behaviour**

**Log file**
Please attach the log file if relevant (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)

**Screenshots**

**Computer used (please complete the following information):**

- OS: [e.g. Linux, Windows, macOS] For macOS, please specify if you have an Intel or M1 CPU (M1 is likely if your mac is new).
- Version [e.g. 18.04]
- Hardware specs [e.g. 128 GB RAM, Xeon 4114 CPU].

**Additional context**

**Comment by alessandrofelder** [comment]
Fixed by @sfmig in #82 - I'll make a release now.
